class AppStrings {
  static String yfdFontFamilyName = 'Mulish';
  static String joinyfd = 'Join yfd';
  static String createYourAccountLongTxt =
      'Create your account and get started with yfd';
  static String createAccountTxt = 'Create Account';
  static String loginTxt = 'Login';
  static String inputEmailAddressTxt = 'Input email address';
  static String emailTxt = 'Email';
  static String inputPasswordTxt = 'Input password';
  static String passWordTxt = 'Password';
  static String alreadyHaveAccountTxt = 'Already have an account? ';
  static String continueWithGoogleTxt = 'Continue with Google';
  static String signupTxt = 'Sign Up';
  static String welcomeBackTxt = 'Welcome back!';
  static String loginToAccessTxt =
      'Log in to access your account and continue your journey with yfd.';
  static String forgotPasswordTxt = 'Forgot Password? ';
  static String resetTxt = 'Reset';
  static String dontHavAccountTxt = "Don't have an account? ";
  static String orText = 'or';
  static String verifyEmailTxt = 'Verify Email Address';
  static String inputEmailLongTxt = 'Kindly input the 5-digit code we sent to ';
  static String otpExpiresInTxt = 'OTP expires in';
  static String proceedTxt = 'Proceed';
  static String didntGetOtpTxt = 'Didn’t get OTP? ';
  static String resendTxt = 'Resend';
  static String setupAuthenticatorTxt = 'Setup Authenticator App';
  static String setupAuthenticatorTxtLong = 'To better safeguard your account, '
      'please set up 2-factor authentication.';
  static String setup2FATxt = 'Setup 2FA';
  static String useTransactionPinInsteadTxt = 'Use a Transaction PIN instead';
  static String createTransactionPinTxt = 'Create Transaction PIN';
  static String createTransactionPinLongTxt =
      'Please enter a secure 4-digit PIN.';
  static String enterSecureTransactionPinTxt = 'Enter 4-digit Transaction PIN';
  static String confirmSecureTransactionPinTxt =
      'Confirm 4-digit Transaction PIN.';
  static String completeTxt = 'Complete';
  static String useAnAuthenticatorLikeTxt = 'Use an authenticator like ';
  static String googleAuthenticatorTxt = 'Google Authenticator';
  static String microSoftAuthenticatorTxt = 'Microsoft Authenticator';
  static String toScanTheQRCodeTxt = 'to scan the QR-code below.';
  static String setupAuthenticatorTxtDirection =
      'To complete setup, enter the 6-digit'
      ' code generated by your authenticator.';
  static String cantScanCodeDirectionTxt =
      'Can’t scan code? Copy the code below to your authenticator app.';
  static String resetPasswordTxt = 'Reset Password';
  static String enterYourEmailAddressTxt = 'Enter your email address.';
  static String confirmText = 'Confirm';
  static String newPasswordTxt = 'New Password';
  static String confirmNewPasswordTxt = 'Confirm New Password';
  static String updateTxt = 'Update';
  static String inputYourNewPassword = 'Please input your new password.';
  static String updatePassowrdTxt = 'Update Password';
  static String toCompleteLoginAuthTxtLong =
      'To complete your login, enter the 6-digit'
      ' code on your authenticator app.';
  static String twoFaAutthenticationTxt = '2FA Authentication';
  static String enterYourTransactionPinTxt =
      'To complete your login, enter your 4-digit transaction PIN.';
  static String transactionPinTxt = 'Transaction PIN';
  static String useAuthenticatorAppInstead = 'Use Authenticator app instead';
  static String forgotTransactionPinTxt = 'Forgot Transaction PIN? ';
  static String resetNowTxt = 'Reset Now';
  static String incorrectPinLongTxt =
      'Incorrect Transaction PIN. Please try again,'
      " or use 'Reset Now' to reset your Transaction PIN";
  static String incorrectAuthenticatorPinLongTxt =
      'Incorrect Authenticator PIN. Please try again';
  static String incorrectEmailOTPText =
      'Incorrect Email OTP. Please check the number'
      ' and try again, or request another.';
  static String createAccountShortTxt = 'Create Account';
  static String walletText = 'Wallet';
  static String totalBalanceText = 'Total Balance';
  static String withDrawText = 'Withdraw';
  static String depositText = 'Deposit';
  static String moreText = 'More';
  static String assetOverViewText = 'Asset Overview';
  static String recentTransactionsText = 'Recent Transactions';
}
